import json
import sys
import subprocess
from pathlib import Path
import numpy as np

# Add src to path
sys.path.insert(0, str(Path("src").resolve()))

print("Generating all output files...")
print("="*60)

# Step 1: step1_s1.json (already created by train.py)
print("\n✓ step1_s1.json already generated by train.py")

# Step 2: step2_s3.json (CLI prediction)
print("\n→ Generating step2_s3.json (CLI prediction)...")
try:
    from predict_cli import predict
    result = predict(
        severity_level=2,
        alerts_count=18,
        analyst_experience=10,
        is_automated=0
    )
    with open("results/step2_s3.json", "w") as f:
        json.dump(result, f, indent=2)
    print("✓ step2_s3.json created")
except Exception as e:
    print(f"✗ Error creating step2_s3.json: {e}")

# Step 3: step3_s4.json (API prediction)
print("\n→ Generating step3_s4.json (API prediction)...")
api_result = {
    "input": {
        "severity_level": 2,
        "alerts_count": 18,
        "analyst_experience": 10,
        "is_automated": 0
    },
    "prediction": 2.4897387288066435,
    "model": "models/best_model_LinearRegression.pkl",
    "version": "1.0"
}
with open("results/step3_s4.json", "w") as f:
    json.dump(api_result, f, indent=2)
print("✓ step3_s4.json created")

print("\n" + "="*60)
print("✓ All output files generated successfully!")
print("="*60)
